pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'Azure subscription 1(5b0205a4-df34-499c-b199-f5bc0d9dce8c)'
      command: 'build'

  - bash: echo hello world