pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'd4809a90-c3d8-4efc-8669-78446e10582c'
      command: 'build'

  - bash: echo hello world

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'd4809a90-c3d8-4efc-8669-78446e10582c'
      appType: 'webApp'
      appName: 'hmtailspin'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'